# Generated by Django 5.1.6 on 2025-03-16 16:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_rename_сalls_communication_calls_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='calls',
        ),
        migrations.RemoveField(
            model_name='communication',
            name='letters',
        ),
        migrations.AddField(
            model_name='communication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communication',
            name='custom_tag',
            field=models.CharField(blank=True, max_length=50, verbose_name='Свой тег'),
        ),
        migrations.AddField(
            model_name='communication',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='communications_files/', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='communication',
            name='tag',
            field=models.CharField(blank=True, choices=[('requirement', 'Требование'), ('clarification', 'Уточнение'), ('revision', 'Правки'), ('deadline', 'Дедлайн'), ('payment', 'Оплата')], max_length=50, verbose_name='Тег'),
        ),
        migrations.AddField(
            model_name='communication',
            name='task',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='crm.task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='communication',
            name='message',
            field=models.TextField(default=23, verbose_name='Текст заметки'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.task')),
            ],
        ),
    ]
